name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: node:18
      ports:
        - 8000:8000
    strategy:
      fail-fast: false
      matrix:
        project: ['chromium']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Install Playwright Browsers
        # we need 1.37.0 to support Firefox install...
        run: npx playwright@next install --with-deps

      - name: Run build:ts
        run: yarn nx run-many --target=build:ts --nx-ignore-cycles --skip-nx-cache

      - name: Run build
        run: yarn nx run-many --target=build --nx-ignore-cycles --skip-nx-cache

      - name: Run E2E tests
        run: yarn test:e2e --setup --concurrency=1 --project=${{ matrix.project }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
